# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - meta
  - on hold
  - EASY
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Cette issue/pull request a été automatiquement marquée comme innactive car elle n'a pas eu d'activité récente.
  Elle sera fermée si il ne se passe rien dans les 14 jours qui viennent. Merci pour votre contribution
  
  This issue/pull request has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true

# Comment to post when removing the stale label.
unmarkComment: >
  Cette issue n'est plus innactive !
  This issue isn't stale anymore!
