---

pipeline:
  test:
    image: python
    commands:
      - apt-get update
      - apt-get install -y hunspell hunspell-fr-comprehensive
      - python3 -m pip install -r requirements.txt
      - BRANCH="$(grep ^BRANCH Makefile | awk '{print $3}')"
      - git fetch origin --no-tags +refs/heads/$BRANCH
      - git branch $BRANCH origin/$BRANCH
      - make verifs
